import type { AuthUser, CameraRecord } from '../types/domain-types.js';

const defaultPreferences = {
  notifyAlerts: true,
  prioritizeFavorites: true,
  rememberLastView: true,
  preferGridView: true,
} as const;

export const seedUsers: AuthUser[] = [
  {
    id: 'usr-001',
    name: 'Carlos Souza',
    email: 'admin@ayel.com.br',
    role: 'administrador',
    passwordHash: '$2b$12$USyP3FoK7KwHcYyCdV9VN.xnUP.J52bBVFzXe4a4DxjxWuiILlK6S',
    profile: 'Administrador',
    status: 'Ativo',
    access: 'Administrador',
    lastAccess: 'Hoje, 08:30',
    unit: 'Matriz',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80',
    phone: '+55 (11) 99876-4521',
    company: 'Ayel Seguranca Patrimonial',
    jobTitle: 'Gestor de Operacoes',
    preferences: { ...defaultPreferences },
  },
  {
    id: 'usr-002',
    name: 'Mariana Lima',
    email: 'mariana.lima@ayel.com.br',
    role: 'cliente',
    passwordHash: '$2b$12$XOfm9oD2YcJRbZ7yZzxcr.XgmaRFbN.RHHydlMn.GU2Aw.2nJgNhq',
    profile: 'Cliente',
    status: 'Ativo',
    access: 'Area restrita',
    lastAccess: 'Hoje, 10:15',
    unit: 'Filial Sul',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=160&q=80',
    phone: '+55 (11) 97777-2211',
    company: 'Ayel Seguranca Patrimonial',
    jobTitle: 'Analista de Monitoramento',
    preferences: { ...defaultPreferences },
  },
  {
    id: 'usr-003',
    name: 'Joao Martins',
    email: 'joao.m@cliente.com',
    role: 'cliente',
    passwordHash: '$2b$12$PRCq7.WvOoS/i3gqmZqFm.NBZLYVH102nAGh3cJ6ujwcNHsTrdmRG',
    profile: 'Cliente',
    status: 'Inativo',
    access: 'Sem acesso',
    lastAccess: '12/03/2026',
    unit: 'Matriz',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',
    phone: '+55 (11) 96666-3322',
    company: 'Cliente Externo LTDA',
    jobTitle: 'Coordenador de Logistica',
    preferences: { ...defaultPreferences },
  },
  {
    id: 'usr-004',
    name: 'Fernanda Rocha',
    email: 'fernanda.r@ayel.com.br',
    role: 'administrador',
    passwordHash: '$2b$12$bkTL793x9ZOi1Dmj5sP3L.wLDNtWflLr1PSNYbYjb57woF3P9eBkO',
    profile: 'Administrador',
    status: 'Ativo',
    access: 'Administrador',
    lastAccess: 'Hoje, 11:42',
    unit: 'Filial Norte',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80',
    phone: '+55 (11) 95555-9988',
    company: 'Ayel Seguranca Patrimonial',
    jobTitle: 'Coordenadora de Seguranca',
    preferences: { ...defaultPreferences },
  },
];

export const seedCameras: CameraRecord[] = [
  {
    id: 'cam-001',
    name: 'Honda 1',
    location: 'Bairro Fontana I, Rua Arapongas, 22, Porto Seguro - BA, 45816-000',
    unit: 'Honda',
    category: 'Recepcao',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/honda-1.jpg',
    streamUrl: 'http://45.236.152.19:8095/70a19d98-18bd-480f-98ce-1b92685a0837.html',
    description: 'Monitoramento da unidade Honda na Rua Arapongas, Bairro Fontana I.',
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-002',
    name: 'Honda 2',
    location: 'Bairro Fontana I, Rua dos Cisnes, 22, Porto Seguro - BA, 45816-000',
    unit: 'Honda',
    category: 'Portaria',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/honda-2.webp',
    streamUrl: 'http://45.236.152.19:8095/211b24f5-004c-42bb-b446-38fa02984a3a.html',
    description: 'Monitoramento da unidade Honda na Rua dos Cisnes, Bairro Fontana I.',
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-003',
    name: 'Verdes Mares 1',
    location: 'Bairro Taperapuan, BR-367, Porto Seguro - BA, 45816-000',
    unit: 'Verdes Mares',
    category: 'Estacionamento',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/verdes-mares-1.jpg',
    streamUrl: 'http://45.236.152.19:8095/aa649b51-3fb9-4adf-b9f5-f3865e1b97b9.html',
    description: 'Monitoramento da unidade Verdes Mares na BR-367, em Taperapuan.',
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-004',
    name: 'Pneus Brasil 1',
    location: 'Bairro Tabapiri, BR-367, Porto Seguro - BA, 45816-000',
    unit: 'Pneus Brasil',
    category: 'Portaria',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/pneus-brasil-1.jpg',
    streamUrl: 'http://45.236.152.19:8095/b11354dd-59bc-4af9-a1a4-9dfdedac6c63.html',
    description: 'Monitoramento da unidade Pneus Brasil na BR-367, em Tabapiri.',
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-005',
    name: 'Villa Brisas 1',
    location: "Estrada Arraial Trancoso, 300 - Arraial d'Ajuda, Porto Seguro - BA, 45816-000",
    unit: 'Villa Brisas',
    category: 'Portaria',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/villa-brisas-1.jpeg',
    streamUrl: 'http://45.236.152.19:8095/7e855ed7-69a5-46d8-839d-98720939dba0.html',
    description: "Monitoramento da unidade Villa Brisas na Estrada Arraial Trancoso, em Arraial d'Ajuda.",
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-006',
    name: 'Eco Village 1',
    location: "Estr. Arraial Trancoso, Arraial d'Ajuda - Porto Seguro, BA",
    unit: 'Eco Village',
    category: 'Estacionamento',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/eco-village-1.webp',
    streamUrl: 'http://45.236.152.19:8095/39239bd3-cd13-4593-9bb8-e0229a1fdb1a.html',
    description: "Monitoramento da unidade Eco Village na Estrada Arraial Trancoso, em Arraial d'Ajuda.",
    updatedAt: 'Atualizado as 19:00',
  },
  {
    id: 'cam-007',
    name: 'Azul Orla',
    location: 'Rua Ararai, Paraiso Pataxos, Porto Seguro - BA, 45810-002',
    unit: 'Azul Orla',
    category: 'Recepcao',
    access: 'public',
    status: 'live',
    quality: 'FHD',
    image: '/images/cameras/azul-orla.webp',
    streamUrl: 'http://45.236.152.19:8095/76a9234c-53de-4237-8fd5-f3779dd3fcfc.html',
    description: 'Monitoramento da unidade Azul Orla na Rua Ararai, Paraiso Pataxos.',
    updatedAt: 'Atualizado as 19:00',
  },
];
