services:
  postgres:
    image: postgres:16-alpine
    container_name: ayel-cams-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ayel_cams
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ayel-cams-postgres-data:/var/lib/postgresql/data

volumes:
  ayel-cams-postgres-data:
